import assert from 'node:assert/strict';
import ts from 'typescript';
import { readFile } from 'node:fs/promises';
const source = await readFile('lib/reactor-engine.ts', 'utf8');
const js = ts.transpileModule(source, { compilerOptions: { target: ts.ScriptTarget.ES2022, module: ts.ModuleKind.ES2022 } }).outputText;
const { makeRoom, runner, apply, advance, blocked, WORLD, LASERS, laserState } = await import('data:text/javascript;base64,' + Buffer.from(js).toString('base64'));
let checks = 0;
const check = (v, text) => { assert.ok(v, text); checks++; };
const time = 1000000;
const act = (r, type, rest = {}, at = time) => apply(r, 'host', { type, requestId: crypto.randomUUID(), ...rest }, at);
const create = () => { const r = makeRoom('ABCDEF', 'host', 'Tester', 'iris', time, true); r.players[0].ready = true; act(r, 'start'); return r; };
let r = create();
check(r.phase === 'countdown' && r.startedAt === time + 3000, 'Three-second shared countdown');
check(r.endsAt === r.startedAt + 90000, 'Shared 90-second deadline');
check(r.players.length === 3 && r.players.filter(p => p.isBot).length === 2, 'Solo has two labelled bots');
check(r.players.every(p => !blocked(p.home.x, p.home.y)), 'All reactors are on reachable floor');
advance(r, r.startedAt - 1); check(r.phase === 'countdown', 'Cannot play early');
advance(r, r.startedAt); check(r.phase === 'playing', 'Countdown starts match');
let p = r.players[0]; p.x = 420; p.y = 240; r.balls = [1,1,2,2,1].map((value, i) => ({ id: i+1, x:p.x, y:p.y, value, expires:0 }));
advance(r, r.simAt + 25);
check(p.bag.length === 3 && p.bag.filter(n => n === 2).length === 1, 'Three slots, at most one golden');
check(p.score === 0, 'Pickup does not score');
p.bag = [1,1,2]; p.x = p.home.x; p.y = p.home.y;
advance(r, r.simAt + 25); check(p.score === 4 && p.bag.length === 0, 'Two blue and one golden deposit four');
advance(r, r.simAt + 25); check(p.score === 4, 'No duplicate deposit');
p.x = 410; p.y = 250; r.balls = []; let at = r.simAt;
apply(r, 'host', {type:'input', x:1, y:1, seq:0, dash:1}, at);
check(Math.hypot(p.input.x, p.input.y) <= 1.000001, 'Diagonal input normalized');
const dashUntil = p.dashUntil, cooldown = p.cooldownUntil;
apply(r, 'host', {type:'input', x:1, y:0, seq:1, dash:2}, at+30);
check(p.dashUntil === dashUntil && p.cooldownUntil === cooldown, 'Dash cooldown cannot be bypassed by counter');
apply(r, 'host', {type:'input', x:-1, y:0, seq:0, dash:9}, at+50);
check(p.input.x === 1 && p.input.dash === 2, 'Old input sequence cannot reverse movement or replay dash');
advance(r, at+800); const stop = {x:p.x,y:p.y}; advance(r, at+1300);
check(p.x === stop.x && p.y === stop.y, 'Movement stops after lost heartbeats');
r = create(); advance(r,r.startedAt); p=r.players[0]; p.x=480;p.y=260;p.bag=[1,2];r.balls=[];
let laserAt = r.startedAt+6500; r.simAt=laserAt-25; advance(r,laserAt);
check(laserState(0,laserAt,r.startedAt)==='on', 'Laser fires only after warning');
check(p.bag.length===1 && r.balls.some(b=>b.value===2&&b.blockedId===p.id), 'Laser drops one ball and blocks instant re-pickup');
advance(r, laserAt+100);check(p.bag.length===1, 'Laser protection prevents repeated drops');
r = create(); advance(r,r.startedAt);r.players=r.players.slice(0,1);p=r.players[0];
r.simAt=r.startedAt+20000-25;advance(r,r.startedAt+20000);
check(r.balls.filter(b=>b.value===2).length===1, 'Rare ball spawns after 20 seconds');
const rare=r.balls.find(b=>b.value===2); check(!blocked(rare.x,rare.y,32) && Math.hypot(rare.x-p.home.x,rare.y-p.home.y)>=85, 'Rare reachable and away from reactors');
r.simAt=rare.expires-25;advance(r,rare.expires);check(!r.balls.some(b=>b.id===rare.id), 'Ground rare expires after 15 seconds');
r.nextRareAt=r.simAt; p.x=420; p.y=240; p.bag=[2];advance(r,r.simAt+25);check(!r.balls.some(b=>b.value===2), 'No new rare while one is carried');
r = create();r.players[0].score=7;r.players[1].score=7;r.players[2].score=3;r.players.forEach(p=>p.bag=[]);r.balls=[];r.simAt=r.endsAt;
advance(r,r.endsAt);check(r.phase==='finished'&&r.winners.length===2,'Top ties share victory');
const scores=r.players.map(p=>p.score);advance(r,r.endsAt+20000);check(JSON.stringify(scores)===JSON.stringify(r.players.map(p=>p.score)), 'Finished scores immutable');
act(r,'rematch',{},r.endsAt+1000);check(r.phase==='lobby'&&r.players.every(p=>p.score===0&&p.bag.length===0),'Rematch resets score and cargo');
check(!r.players[0].ready && r.players[1].ready, 'Humans ready again; bots stay ready');
const duplicate=crypto.randomUUID();apply(r,'host',{type:'duration',value:60,requestId:duplicate},r.simAt+10);apply(r,'host',{type:'duration',value:120,requestId:duplicate},r.simAt+20);check(r.duration===60,'Control request IDs are idempotent');
r=makeRoom('ABCDEF','host','Tester','iris',time,false);r.players.push(runner('guest','Guest','jet',time));r.players[1].lastSeen=time+16000;advance(r,time+16000);check(r.hostId==='guest','Active human becomes host after 15 seconds');
for (const n of [2,3,6]) {
  r=makeRoom('ABCDEF','host','Tester','iris',time,false);act(r,'bots',{value:n-1});act(r,'ready',{ready:true});act(r,'start');
  const started=performance.now();
  for(let t=r.startedAt;t<=r.endsAt;t+=200){r.players[0].lastSeen=t;advance(r,t);}
  check(r.phase==='finished'&&r.players.length===n,`Complete ${n}-participant match`);
  check(r.players.slice(1).every(p=>p.score>0),`All ${n-1} bots navigate and deposit`);
  check(r.players.every(p=>!blocked(p.x,p.y)),`All ${n} runners stay inside map`);
  console.log(`${n} participants: bot scores ${r.players.slice(1).map(p=>p.score).join(', ')}; 90s simulation ${Math.round(performance.now()-started)}ms`);
}
console.log(`Passed ${checks} Reactor Rush rule checks.`);
